-- AUTO_INCREMENT is H2/MySQL dialect.
-- For portable ANSI SQL use: id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
CREATE TABLE bets (
    id                 BIGINT         AUTO_INCREMENT PRIMARY KEY,
    user_id            VARCHAR(255)   NOT NULL,
    event_id           VARCHAR(255)   NOT NULL,
    event_market_id    VARCHAR(255)   NOT NULL,
    selected_winner_id VARCHAR(255)   NOT NULL,
    bet_amount         DECIMAL(19, 4) NOT NULL,
    status             VARCHAR(20)    NOT NULL
);

-- Composite index covering the hot query path: findPendingByEventId(eventId)
-- A partial index on status='PENDING' would be preferable in production (PostgreSQL: WHERE status = 'PENDING').
CREATE INDEX idx_bets_event_pending ON bets (event_id, status);
